### PR TITLE
Added arpTableSolver

### PR DESCRIPTION
**Pull request by luisllamasbinaburo**
Branch with arpTableSolver, for use in ZeroConf funcionality
Dependencies:
```
"@network-utils/arp-lookup": "^1.0.4"
"net-ping": "^1.2.3"
```

### CODE REVIEW

**Comment by skydiver** [comment]
Hey @luisllamasbinaburo 

Here are some numbers according to this page, https://bundlephobia.com/:

| package                   | MINIFIED | MINIFIED + GZIPPED |
|---------------------------|----------|--------------------|
|          net-ping         | 10.7kB   |        3.2kB       |
| @network-utils/arp-lookup | 1.5kB    | 761B               |
| ewelink-api               | 839kB    | 228.2kB            |

Here are more info:
https://bundlephobia.com/scan-results?packages=@network-utils/arp-lookup@1.0.4,net-ping@1.2.3,delay@4.3.0,nonce@1.0.4,random@2.1.1,request@2.88.0,request-promise@4.2.4,websocket@1.0.30,websocket-as-promised@0.10.1

https://bundlephobia.com/scan-results?packages=delay@4.3.0,nonce@1.0.4,random@2.1.1,request@2.88.0,request-promise@4.2.4,websocket@1.0.30,websocket-as-promised@0.10.1

So, looks like adding these 2 packages have a insignificant overhead.

**Comment by skydiver** [comment]
I have a few questions here:

1. how do you initialize this class? something like this?
```
const arpTableSolver = require('./lib/arpTableSolver.js');
(async () => {
  const arp = new arpTableSolver();
  await arp.Init();
]})();
```

2. `GetIp` is not called on the class. what is the purpose of this method?

3. tried `await arp.getTable()` manually but always get an empty array

**Comment by luisllamasbinaburo** [comment]
Hello, 

1) I use this way
```js
(async () => {
  const ipres = new IpResolver();
  await ipres.Init();
  await ipres.SaveArpTable('arptable.json');
})();
```
and once I have the 'arptable.json', at anytime
```js
(async () => {
  let arpTable = await ipres.loadArpTable('arptable.json');
})();
```

But it is really strange, because this is basically the same that your did, and you are getting any empty array. I don't understand. Which OS are you using? (I tried in Win10)

On the other hand, `GetIP(mac)` method is provided to be used on the Ewelink connection for ZeronConf. But I didn't include in this branch, because I don't want to 'mess' your code.
I try to keep them independent, and leave this branch only for showing the arpTable
(that it seems, doesn't work for you, but i don't know why)

**Comment by skydiver** [comment]
Found the problem:
Looks like `@network-utils/arp-lookup` doesn't work on macos.
The parser method doesn't understand the response from `arp -a` (which is different from windows)

Also, tested on linux with same result.

I'm looking for another npm package to get mac/ips

**Comment by luisllamasbinaburo** [comment]
Ok, I'm going to test it

**Comment by skydiver** [comment]
Hello @luisllamasbinaburo 

I've made some changes to the class using the new library.

I was able to export a json file with the ip/mac associations.

Let me know if it works for you so we can merge and continue with the other PR.


Thanks.-

**Comment by luisllamasbinaburo** [comment]
Yes, it works perfectly. (Sorry for the late reply)
Let me know if i can do anything more
Thanks!

**Pull request merged**
