### PR TITLE
Release v1.10.0

### PR DESCRIPTION
**Pull request by skydiver**
* keep socket connection opened
* new `getCredentials` method who replaces `login`
* deprecated `login` method
* renamed region mixin
* added new test cases

### CODE REVIEW

**Comment by ttz642** [comment]
> * new `getRegion` method who replaces `login`

New method is **getCredentials** _which_ replaces `login`

**Comment by ttz642** [comment]
**openWebSocketMixin.js** -- suggestion

change:
```
    wsp.onMessage.addListener(message => {
      try {
        const data = JSON.parse(message);
        callback(data);
      } catch (error) {
        callback(message);
      }
    });
```
to:

```
    wsp.onMessage.addListener(message => {
      if(message == "pong"){//eat pong...
		//Can be left out in final code after testing //////////////////
		date = new Date();
		console.log("keepalive received at:",date.toUTCString());
		////////////////////////////////////////////////////////////////
       }else{
         try {
          const data = JSON.parse(message);
          callback(data);
        } catch (error) {
          callback(message);
        }
      }
    });
```

**Comment by skydiver** [comment]
Hey @ttz642 

I prefer to keep the "pong" reply and let everyone filters the message they need.

I'm thinking if you're creating a web dashboard, that message will be useful to indicate open connections or current activity.

**Comment by ttz642** [comment]
> I prefer to keep the "pong" reply and let everyone filters the message they need.
> 
> I'm thinking if you're creating a web dashboard, that message will be useful to indicate open connections or current activity.
> 
> What i'm thinking to do, it's to return an object with the pong message so you can always treat the response as a valid object.

I was thinking if you just drop the pong and raise an event that the connection has dropped / closed for whatever reason so the main code could call socket.close() and re-open.

In the calling code has a listener waiting for the error, eg:

```
wsp.on( 'error', function( err ) {
   // handle the error...
} );
```
Using a couple of variables for when ping is sent and pong received you'd know if the link is up, eg:
```
if ( (wsp.pingreceived - wsp.pingsent) > -120 ) {//pong received within last 2 minutes, 120000 if time in mS
}else{//looks like connection to server dropped
    // close socket and re-open
}
```

BTW: Not an expert in nodejs/javascript yet, only recently moved from perl...

**Comment by ttz642** [comment]
Proposed release v1.90.0 ?

Martin,
Any chance you could create a working branch say version v1.90.0 which is based on v1.10.0 updated with:

- arpTableSolver #18 
- Zero Conf functionality (LAN mode) #17 
- documentation in README.md #42 

I'l test and hopefully you can release v2.0.0 for xmas :-)

**Pull request merged**
