### PR TITLE
Release v2.0.0

### PR DESCRIPTION
**Pull request by skydiver**
* added zeroconf functionality (LAN mode)
* created arpTableSolver class

### CODE REVIEW

**Comment by skydiver** [comment]
Hey @luisllamasbinaburo 

Have you seen this huge PR?

Anything to say before merge and release 2.0?

Have you tried zeroconf feature?

Thanks for your help!

**Comment by luisllamasbinaburo** [comment]
Hi! I used the holidays to test 2.0.0. I like the Zeroconf funtionality. It's pretty cool.
But I'm still facing some problems with saving ArpTable.
I will test tonight and tomorrow and I will tell you

**Comment by luisllamasbinaburo** [comment]
Hello again. I have tested and unfortunately it seems that ARPPING have some issues on Windows.
But i have created a PR to your ARPPING fork that should work correctly both on Linux and Windows
https://github.com/skydiver/arpping/pull/2

**Comment by skydiver** [comment]
Hey @luisllamasbinaburo 

ARPPING package was updated, let me know if it worked.

Thanks.-

**Comment by luisllamasbinaburo** [comment]
Yes, now it works correctly on Windows too :thumbsup:

**Pull request merged**
