### PR TITLE
Add typescript typings for main.js

### PR DESCRIPTION
**Pull request by BMXsanko**

### CODE REVIEW

**Comment by skydiver** [comment]
Hello @BMXsanko, thanks for the PR.

This PR looks good to me, i'm gonna merge.

Can you post a quick comment on how it works?
I'm not a ts user but will be great to have a general idea of using "typings".


Thank you.

**Comment by BMXsanko** [comment]
Hi, the `.d.ts` files are declaration files, basically, they are templates for the types, that typescript uses if the code is written in JS. The "typings" or "type" parameter, in the package.json basically declares where the main .d.ts file is you can found more info about this: [here](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html)
Also [here](https://devblogs.microsoft.com/typescript/writing-dts-files-for-types/) is a good explanation about `.d.ts` files.

**Comment by skydiver** [comment]
thank you @BMXsanko

**Comment by skydiver** [comment]
thank you @BMXsanko

**Pull request merged**
