### PR TITLE
Added Zero Conf functionality (LAN mode)

### PR DESCRIPTION
**Pull request by luisllamasbinaburo**
Added crypto functions, used for using Sonoff in "LAN" mode (directly by IP, without Internet conection)
Requires Crypto-JS library

### CODE REVIEW

**Comment by skydiver** [comment]
Hello @luisllamasbinaburo 

Thanks for this amazing PR.

Can you post a script on how to use this?

Something like:

```
const ewelink = require('ewelink-api');

/* instantiate class */
const conn = new ewelink({
  email: '<your ewelink email>',
  password: '<your ewelink password>',
});

/* get all devices */
const devices = await conn.getDevices();
console.log(devices);
```

Thank you.-

**Comment by luisllamasbinaburo** [comment]
Yes, of coures
First, we have to use a full login connecion to save the 'deviceCache' (you only have to do this one time)
```js
async function devicesToJson(connection) {
  const devices = await connection.getDevices();

  var jsonContent = JSON.stringify(devices); 5
  fs.writeFile("devices.json", jsonContent, 'utf8', function (err) {
    if (err) {
      console.log("An error occured while writing JSON Object to File.");
      return console.log(err);
    }
  });
}
```

When you have your 'devices.json' file, you need a 'arpTable', that have IP-MAC association in you LAN network (I have an object that generates this arpTable, we could talk about this step later)
```js
async function loadCachedDevices() {
  let jsonContent = fs.readFileSync('devices.json');
  return JSON.parse(jsonContent)
}

async function loadArpTable() {
  let jsonContent = fs.readFileSync('arpTable.json');
  return JSON.parse(jsonContent)
}

(async () => {
  let devicesCache = await loadCachedDevices();
  let arpTable = await loadArpTable();

  var connection = new eWeLink({ devicesCache, arpTable });
  await connection.setDevicePowerState(DEVICE_XXX_ID, 'on', 1)
})();
```

If the user have both elements (deviceCache and arpTable) the use of 'ZeroConf' is the same that 'Online', but much faster, doesn't requires internet connection, and have no risk to be banned by Sonoff.

But I still have to improve the 'online' / 'ZeroConf' mode switch. For example, it should try to use ZeroConf, and if we have error as result, try to use Online method
But I dont want to put all this code in the first commits, before knowing your opinion

**Comment by skydiver** [comment]
Ok, so, here is what i did:

1. created `devices.json` with your code, no problems here
2. find one of my sonoff ip address
3. hardcoded the ip on `getLocalIp`, to always return the same ip address

called this script:

```
(async () => {
  const devicesCache = await loadCachedDevices();

  // here i've ignored the arpTable because i'm returning a hardcoded ip
  const connection = new ewelink({ devicesCache });
  await connection.setDevicePowerState('my sonoff id', 'toggle');
})();
```

the POST to the ip address returns `{ seq: 31, sequence: '1561818131123', error: 0 }` which looks good because can connect, but no power state is updated ...

any ideas?

**Comment by luisllamasbinaburo** [comment]
for the moment, try   
```js
await connection.setDevicePowerState('my sonoff id', 'on'); // or 'off'
```
'togle' depends on the current device state, and you get that using an 'online' request.
I have to implement some funcionalty to get the current state in 'ZeroConf'
I believe that we can do that using a request to `http://[ip]:[port]/zeroconf/info
with body
```json
{ 
	"deviceid": "my sonoff id", 
	"data": { } 
 }
```

**Comment by skydiver** [comment]
ok, it worked!

the problem was i'm using single channel device, so i pointed the url to `http://[ip]:[port]/zeroconf/switch` and turned on/off successfully 

so, my thoughts on the lan mode is we can't make the default method because:
* not every device has lan mode 
* people can be using the package on a remote server

i think the best will be to pass device ip on the connection method, like:

```
/* instantiate class */
const conn = new ewelink({
  ip: '1.2.3.4',
});
```

and if there is an ip use lan mode (and return an error if there is no response)

what do you think?

**Comment by luisllamasbinaburo** [comment]
What I have in mind is somethink like:
- User provide login information only (at, or email + pass) => ok, I go online mode only
- User provide cache information (devicesCache + ip-somehow) => ok, i go ZeroConf mode only
- User provide both login and cache => ok, i go try ZeroConf, and if not posible try online mode

On the other hand, the reason for use arpTable, instead of pass the Ip, is that your object 'Connection' abstract a connection to multiple devices, and you access individual devices by its deviceId
'devices.json' doesn´t contains IP information, but i does contains Mac address.
And, in and small network, it's easy to obtain the arptable that joins local ip with Mac address
(I can provide the code for that in another branch if you want. It's not long, but a little tricky, and have some dependences. That is why I didn't include in this branch, and the arpTable as a constructor parameter)

**Comment by skydiver** [comment]
Ok @luisllamasbinaburo, sounds good to me, my main concern is about adding more dependencies for to build the arpTable, but let's see how it progress.

I say to start by doing `User provide cache information (devicesCache + ip-somehow) => ok, we go ZeroConf mode only` and make the third point later, to not have a huge PR.

Also, maybe we can add on a new PR the required code to prepare the lan stuff, like `loadArpTable` and `devicesToJson` then once merged, we can continue by linking to this PR.

Thoughts ?

**Comment by luisllamasbinaburo** [comment]
Ok perfect, I agree. That is exactly why I don't add the arpTable, because I didn't want to add more references. In fact, is not a 'Sonoff API'. 
If user is able to provide this ip-mac relationship table from any other method (another library, from his router config, manually entered... whatever) it's independient from 'Sonoff API'

I will put the code in another PR, and we will see how to put both parts together in a "clean" way

**Comment by ttz642** [comment]
If you add a group to the server and add all LAN capable devices to this group when you download the device info you will see this group against the devices which are lan capable!

I created a group LANCAPABLE and added my two devices into it now when I get device info I see the device is part of the group. Although it doesn't report the group name in text but gives a reference, eg:

`    groups: [ '5dc8227d5c833e64197ddfb2' ],`

**Comment by skydiver** [comment]
Hey @luisllamasbinaburo 

There was too many conflicts to rebase this branch with master so i opened a new one: https://github.com/skydiver/ewelink-api/pull/46 (i'm gonna close this PR).

The zeroconf feature will not be possible without your help.

Thanks a lot.

**Pull request closed without merging**
