### PR TITLE
Include documentation in README.md

### PR DESCRIPTION
**Pull request by ttz642**
If the complete documentation is included within the README.md file then the documentation is associated with the revision of code and can be updated as code developed and when released documentation is updated.

To see the README.md formatted see:

- https://github.com/ttz642/ewelink-api

BTW: Never contributed to github before so learning my way around it.

--
Steve

### CODE REVIEW

**Comment by skydiver** [comment]
Hey @ttz642 

Thanks for all your work.

I'm not very fan of the idea to add all this text to the README file, we already have a nice organized docs site.

I agree on the original problem about documentation by package version.

I think i prefer to keep different versions of the docs uploaded and one master with the current state.

Also, i'm gonna make a public repo with the docs site so everyone can suggest changes and make improvements.

**Comment by ttz642** [comment]
> I'm not very fan of the idea to add all this text to the README file, we already have a nice organized docs site. Maintaining docs on multiple places will be difficult.
This is how many (if not all) packages are documented on github.

> I agree on the original problem about documentation by package version.
Having the documentation separate means users using old or newer packages are not documented. Only the official release is documented,

> I think i prefer to keep different versions of the docs uploaded and one master with the current state.
Where are you proposing the documentation by version?

> Also, i'm gonna make a public repo with the docs site so everyone can suggest changes and make improvements.
A wiki site rather than a bulletin board?

Don't get me wrong your documentation site is nice to read and clean but I still think we should have the original in the README.md and you can sync your website with the master released branch.

Just my thoughts...
-- 
Steve

**Comment by skydiver** [comment]
Hey @ttz642 

In version 2.0, docs will be part of the repo but separated by documents.

Will close this PR.

Thanks for the help and the idea..

**Comment by ttz642** [comment]
Martin,
> In version 2.0, docs will be part of the repo but separated by documents.

If your putting documents in multiple files perhaps it would make sense to put them in the same directory as the code?

eg:
`/docs/available-methods/getdevice.md   ==>>   /mixins/devices/getdevice.md
`
May encourage updates to docs as you don't have to look elsewhere to see them and if your looking at the code no searching.

--
Steve

**Pull request closed without merging**
